### ISSUE TITLE
How to use the wgo to watch my local SGF games?

### ISSUE THREAD

**Issue by CGLemon** [zakki/cgos#14]
I want check my SGF writer with the ```wgo_view```. But I do not really understand the JavaScript. How to use it on local? Thanks!

**Comment by zakki** [comment]
1. Concat and minimize sources using `cd wgo_view && ./build.sh`
2. Add wgo tag to html  `<div data-wgo="path/to/your.sgf" style="width: 700px" >` like http://203.138.189.63/cgos/viewer.cgi?19x19/SGF/2023/02/01/1232.sgf
3. Start http server `python3 -m http.server&` and open `http://localhost:8000/your.html`, because browser can't use ajax over file:// protocol.
    - I don't know well, but If you use inline sgf, you may be able to use file protocol.

**Comment by CGLemon** [comment]
Thank It works well.
